### ISSUE TITLE
(Classes) Bug in description of DBUtil class

### ISSUE THREAD

**Issue by SCIF** [fuel/docs#337]
In classes/database/dbutil.html#/method_create_table in `Possible parameters` section written:

> constraint Length or values. Values can be provided in an array

I tried put `array('val', 'val2')` in `constraint` field and got error.

But in fact, after DBUtil code revision i figured out that text must be same:

> Values can be provided in double quotes as comma separated list.

**Comment by WanWizard** [comment]
Too bad you don't tell us which error you got (which could indicate it's a code error, and not a docs error).

Constraint can be a scalar value or an array of values. If an array is passed, it will be converted to a comma separated list of strings like "('val', 'val2')" which to me is correct.

**Comment by SCIF** [comment]
Hm. What's for error code?? I wrote about incomprehensible sentense in docs about DBUtil method. I thought that `can be provided in an array` means code like `array('val', 'val2')` nor `"('val','val2')"`. If add there example — it'll be very clearer.

**Comment by WanWizard** [comment]
"Multiple values can be provided in an array" indeed means that:
- simple value: "val"
- multiple values: array('val1', 'val2')

And not as a string "('val1', 'val2')", although in this particular example that might work because you know the current method internals (which might change without notice and break your application).

Your original message says that the correct syntax using an array produces an error in your case, hence my question about which error...

**Comment by SCIF** [comment]
Sorry. My mistake. I use release 1.1 and dev-docs. After checkouting to 1.1/develop branch all code described in docs become working. I just hope that api of dbutil class didn't changed after release 1.1, but i mistaked.
