### ISSUE TITLE
Migrations in modules

### ISSUE THREAD

**Issue by ghost** [fuel/docs#49]
Two questions. 

Is anyone currently working on having migrations inside of modules? 

If you are is there anywhere I can check in the future to answer these questions so I don't have to bug you?

Well, maybe three questions. If it's not currently in development, I'm going to develop it myself. Would you rather I develop a separate class or add it into the current one?

**Comment by philsturgeon** [comment]
The forums are for chatting, this is mainly for "I have found a bug".

Now, migrations in Modules sound like they make sense, but really they should never exist. I have thought this over many times and I really don't want to see it in Fuel.

Why? Migrations are a timeline in the database of the application as a whole. They assume knowledge over the entire thing and keep your application in check. If modules start messing with the database it will lead to confused ordering. 0025 is in a module, 0019 is in the app, huh? We have two 0025's, ARG.

Basically you probably want migrations in modules because you want install/upgrade logic right?

Well I have migrations in CodeIgniter/PyroCMS and I use Modules, but I have implemented the install/upgrade logic separately. A module should not be able to interfere with the timeline of the application as a whole, but it definitely should be able to install itself and upgrade itself.

Sadly that is not something for Fuel to be concerned with as the implementation of install/upgrade/delete will be totally different for every application/CMS that is built with it.
