### ISSUE TITLE
before()

### ISSUE THREAD

**Issue by acidm** [fuel/docs#590]
before()... " It will not be called if that method turns out not to exist. " This is not true, before method is called always.This is a bug in docs or core? When she should be called?

**Comment by WanWizard** [comment]
Obviously, the docs are correct. And so is the code.

If it would always be called, you would get a `method before() not defined` on the first controller that doesn't have a before method...

**Comment by acidm** [comment]
Ok please tell me why ,if i called not existed method "tester->noexists()" my request is redirected...
My request: 
http://localhost/index.php/tester/noexists/

All config in fuelphp is default.

And code:
<?php

class Controller_Tester extends Controller
{

```
public function before()
{
     return Response::redirect('http://www.google.pl');
}

public function action_work()
{
return Response::forge('Worked,worked,werked');
}
```

}

PS.sorry for my  english ...  :)

**Comment by frankdejonge** [comment]
@acidm the before function is a substitute for a __constructor function. Because we use the constructor internally to set the Request and check for internal routing, we allow users to specify the before method. In your case, the before method redirects the user away, like with a normal constructor, this is always called. That's why it's redirected.

**Comment by acidm** [comment]
Ok thanks  :) ,  but why in the docs is write " It will not be called if that method turns out not to exist." ?

**Comment by frankdejonge** [comment]
It's if the before method does not exists in the controller class, not the other method.

**Comment by acidm** [comment]
ok thanks again  :)
