### ISSUE TITLE
(Auth) SimpleAuth pages

### ISSUE THREAD

**Issue by jschreuder** [fuel/docs#78]

**Comment by jonstuebe** [comment]
It would be helpful to have usage docs on function such as create_user and update_user as well as documentation on how to successfully use the has_access (acl) function within SimpleAuth.

**Comment by trideetztz** [comment]
I just wanted to point something minor out..

I'm getting used to the FuelPHP coding standards myself since they're a little different from what I used to use but it would be nice to fix this in the examples on these pages.

I'm referring to the if statements missing a space

Like this:
if($_POST) --> if ($_POST)

I know, I know, it's stupid..but still :)

**Comment by WanWizard** [comment]
Simpleauth has been documented before the 1.2 release.
